service:
  name: uniswap-api-auth

frameworkVersion: ">=1.75.1 <2.0.0"

provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs12.x
  memorySize: 320 # optional, in MB, default is 1024
  timeout: 20 # optional, in seconds, default is 6
  logRetentionInDays: 1
  apiKeys:
    - low:
        - TEST_API_KEY
        - yIUHxhxhwP
        - ufxxSsdRrB
        - setudwgeMI
        - pKlGUlgrkV
        - dAcHvVqcaR
        - nVDzSKvsKS
        - YSbeEYACJs
        - oIdwHwSSXx
        - yBMIcmKTGj
        - kNsdnRebNm
        - hhKIoosmpJ
        - vKUsOeHgoX
        - dXLuUQNcVD
        - VieGsbhHec
        - NTpdZhNBxm
        - izPomEygRE
        - UZPPvKX6l1
        - PNcYknUTqy
        - VN50kkZEQI
        - cBe13HPpll
        - 8yHjwNSrim
        - 8hhD0ZfjRD
        - qaQj0g3vH9
        - NMp3sBgNEk
        - lNrVRqdXdf
        - p8idnRO9GC
        - bvB3Z3NbDm
        - zsmy4mC7Tx
        - wfZCQXXJbs
        - qPJ8zA1Rn0
        - aQyVkeFJII
        - mB3CSraA8T
        - fAO8AZLbQE
    - medium:
        - COINMARKETCAP_API_KEY
        - GbrOiQnhbE
        - hoBoxSZDSr
        - XufHyw87Ae
        - qMhEkai3bB
        - RoaHDgKAhb
        - AWsHhhEwUx
        - 4LQCKVk0vR
        - sJ5M9hxrm1
        - pH8JxYytcI
        - 75cuj2bkyw
        - H9ruGLVhUx
        - TwVPzztRXM
        - U0IdLesY5B
        - nrClJ0PWhN
        - 4S2KR4csrv
        - AmSu8dL7BP


  usagePlan:
    - low: # 5 QPS
        quota:
          limit: 500000 # 5 * 60 * 60 * 24
          period: DAY
        throttle:
          burstLimit: 10
          rateLimit: 5
    - medium: # 50 QPS
        quota:
          limit: 5000000 # 50 * 60 * 60 * 24 rounded up
          period: DAY
        throttle:
          burstLimit: 100
          rateLimit: 50
    - high: # 100 QPS
        quota:
          limit: 10000000 # 100 * 60 * 60 * 24 rounded up
          period: DAY
        throttle:
          burstLimit: 200
          rateLimit: 100

custom:
  # Enable or disable caching globally
  apiGatewayCaching:
    enabled: true
    clusterSize: '0.5' # defaults to '0.5'
    ttlInSeconds: 300 # defaults to the maximum allowed: 3600
  contentEncoding:
    minimumCompressionSize: 0 # Minimum body size required for compression in bytes

plugins:
  - serverless-plugin-typescript
  - serverless-api-gateway-caching
  - serverless-content-encoding

functions:
  v1-summary:
    handler: src/v1/summary.handler
    events:
      - http:
          method: get
          path: /v1/summary
          private: true
          caching:
            enabled: true
            ttlInSeconds: 900

  v1-tickers:
    handler: src/v1/tickers.handler
    events:
      - http:
          method: get
          path: /v1/tickers
          private: true
          caching:
            enabled: true
            ttlInSeconds: 60

  v1-assets:
    handler: src/v1/assets.handler
    events:
      - http:
          method: get
          path: /v1/assets
          private: true
          caching:
            enabled: true
            ttlInSeconds: 3600

  v1-orderbook:
    handler: src/v1/orderbook.handler
    events:
      - http:
          method: get
          path: "/v1/orderbook/{pair}"
          private: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.pair
            ttlInSeconds: 3600


  v1-trades:
    handler: src/v1/trades.handler
    events:
      - http:
          method: get
          path: "/v1/trades/{pair}"
          private: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.pair
            ttlInSeconds: 900

  v2-summary:
    handler: src/v2/summary.handler
    events:
      - http:
          method: get
          path: /v2/summary
          private: true
          caching:
            enabled: true
            ttlInSeconds: 900

  v2-tickers:
    handler: src/v2/tickers.handler
    events:
      - http:
          method: get
          path: /v2/tickers
          private: true
          caching:
            enabled: true
            ttlInSeconds: 60

  v2-assets:
    handler: src/v2/assets.handler
    events:
      - http:
          method: get
          path: /v2/assets
          private: true
          caching:
            enabled: true
            ttlInSeconds: 3600

  v2-orderbook:
    handler: src/v2/orderbook.handler
    events:
      - http:
          method: get
          path: "/v2/orderbook/{pair}"
          private: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.pair
            ttlInSeconds: 3600

  v2-trades:
    handler: src/v2/trades.handler
    events:
      - http:
          method: get
          path: "/v2/trades/{pair}"
          private: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.path.pair
            ttlInSeconds: 900
